### ISSUE TITLE
the proposed solution for internationalization doesn't work

### ISSUE THREAD

**Issue by artm** [derekprior/datejs-rails#6]
If I require `date/nl-NL` after `date` (like suggested) the `CultureInfo` gets set, but not used by the library.  If I require `date/nl-NL` before `date` the latter overrides `CultureInfo` with en-US.

This is due to the way they [close over the value of CultureInfo at the moment it was loaded](https://github.com/derekprior/datejs-rails/blob/master/vendor/assets/javascripts/date/core.js#L13) (and they do the same thing in other sources).

My solution was: require the localization, then individual parts:

//= require date/nl-NL
//= require date/core
//= require date/parser
//= require date/sugarpak
//= require date/time

**Comment by derekprior** [comment]
This project is now archived. See note in README for more detail.
